name: Auto Update AdBlock Rules

on:
  schedule:
    # 每10分钟运行一次
    - cron: '*/10 * * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - main

# 添加权限配置
permissions:
  contents: write

jobs:
  update-rules:
    runs-on: ubuntu-latest
    # 添加超时设置
    timeout-minutes: 10
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # 设置Python环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 安装依赖（增加重试机制）
      - name: Install dependencies with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i to install dependencies"
            if python -m pip install --upgrade pip && pip install requests; then
              echo "Dependencies installed successfully"
              break
            else
              echo "Attempt $i failed"
              if [ $i -eq 3 ]; then
                echo "All attempts failed"
                exit 1
              fi
              sleep 5
            fi
          done

      # 设置Git配置
      - name: Setup Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # 更新广告拦截规则
      - name: Update AdBlock rules
        run: |
          python scripts/update_rules.py

      # 检查是否有变更并提交
      - name: Commit and push changes
        run: |
          git add .
          # 检查是否有变更
          if ! git diff --staged --quiet; then
            git commit -m "Auto update rules at $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
            # 添加推送重试机制，处理non-fast-forward错误
            for i in {1..3}; do
              echo "Attempt $i to push changes"
              if git push; then
                echo "Changes committed and pushed successfully"
                break
              else
                echo "Push attempt $i failed, trying to pull first"
                if git pull --rebase; then
                  echo "Pull successful, retrying push"
                  if git push; then
                    echo "Changes committed and pushed successfully after pull"
                    break
                  fi
                fi
                if [ $i -eq 3 ]; then
                  echo "All push attempts failed"
                  exit 1
                fi
                sleep 5
              fi
            done
          else
            # 即使没有变更也创建空提交以确保定时更新
            git commit --allow-empty -m "Auto update rules at $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') (no changes)"
            # 添加推送重试机制，处理non-fast-forward错误
            for i in {1..3}; do
              echo "Attempt $i to push empty commit"
              if git push; then
                echo "Empty commit created and pushed successfully"
                break
              else
                echo "Push attempt $i failed, trying to pull first"
                if git pull --rebase; then
                  echo "Pull successful, retrying push"
                  if git push; then
                    echo "Empty commit pushed successfully after pull"
                    break
                  fi
                fi
                if [ $i -eq 3 ]; then
                  echo "All push attempts failed"
                  exit 1
                fi
                sleep 5
              fi
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
